[2025-10-20T05:55:11.106+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-10-20T05:55:11.117+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: events_analytics_pipeline.dbt_run manual__2025-10-20T05:27:54.969341+00:00 [queued]>
[2025-10-20T05:55:11.121+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: events_analytics_pipeline.dbt_run manual__2025-10-20T05:27:54.969341+00:00 [queued]>
[2025-10-20T05:55:11.122+0000] {taskinstance.py:2306} INFO - Starting attempt 3 of 3
[2025-10-20T05:55:11.127+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): dbt_run> on 2025-10-20 05:27:54.969341+00:00
[2025-10-20T05:55:11.131+0000] {standard_task_runner.py:63} INFO - Started process 875 to run task
[2025-10-20T05:55:11.134+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'events_analytics_pipeline', 'dbt_run', 'manual__2025-10-20T05:27:54.969341+00:00', '--job-id', '40', '--raw', '--subdir', 'DAGS_FOLDER/events_pipeline_dag.py', '--cfg-path', '/tmp/tmpv7w0yjvv']
[2025-10-20T05:55:11.135+0000] {standard_task_runner.py:91} INFO - Job 40: Subtask dbt_run
[2025-10-20T05:55:11.157+0000] {task_command.py:426} INFO - Running <TaskInstance: events_analytics_pipeline.dbt_run manual__2025-10-20T05:27:54.969341+00:00 [running]> on host 0d320e139cdc
[2025-10-20T05:55:11.192+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='data-team' AIRFLOW_CTX_DAG_ID='events_analytics_pipeline' AIRFLOW_CTX_TASK_ID='dbt_run' AIRFLOW_CTX_EXECUTION_DATE='2025-10-20T05:27:54.969341+00:00' AIRFLOW_CTX_TRY_NUMBER='3' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-10-20T05:27:54.969341+00:00'
[2025-10-20T05:55:11.192+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-10-20T05:55:11.198+0000] {events_pipeline_dag.py:148} INFO - Running command: dbt run --profiles-dir /opt/***/.dbt --project-dir /opt/***/event_gen
[2025-10-20T05:55:13.669+0000] {events_pipeline_dag.py:167} ERROR - dbt run failed with error:

[2025-10-20T05:55:13.670+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-10-20T05:55:13.670+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/events_pipeline_dag.py", line 175, in dbt_run
    return run_dbt_command("run", **context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/events_pipeline_dag.py", line 151, in run_dbt_command
    result = subprocess.run(
             ^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['dbt', 'run', '--profiles-dir', '/opt/airflow/.dbt', '--project-dir', '/opt/airflow/event_gen']' returned non-zero exit status 1.
[2025-10-20T05:55:13.675+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=events_analytics_pipeline, task_id=dbt_run, run_id=manual__2025-10-20T05:27:54.969341+00:00, execution_date=20251020T052754, start_date=20251020T055511, end_date=20251020T055513
[2025-10-20T05:55:13.680+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 40 for task dbt_run (Command '['dbt', 'run', '--profiles-dir', '/opt/airflow/.dbt', '--project-dir', '/opt/airflow/event_gen']' returned non-zero exit status 1.; 875)
[2025-10-20T05:55:13.687+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-10-20T05:55:13.701+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-10-20T05:55:13.704+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
