[2025-10-20T05:50:10.277+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-10-20T05:50:10.291+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: events_analytics_pipeline.dbt_run manual__2025-10-20T05:45:03.898078+00:00 [queued]>
[2025-10-20T05:50:10.296+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: events_analytics_pipeline.dbt_run manual__2025-10-20T05:45:03.898078+00:00 [queued]>
[2025-10-20T05:50:10.296+0000] {taskinstance.py:2306} INFO - Starting attempt 2 of 3
[2025-10-20T05:50:10.311+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): dbt_run> on 2025-10-20 05:45:03.898078+00:00
[2025-10-20T05:50:10.319+0000] {standard_task_runner.py:63} INFO - Started process 699 to run task
[2025-10-20T05:50:10.322+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'events_analytics_pipeline', 'dbt_run', 'manual__2025-10-20T05:45:03.898078+00:00', '--job-id', '30', '--raw', '--subdir', 'DAGS_FOLDER/events_pipeline_dag.py', '--cfg-path', '/tmp/tmptd__nw95']
[2025-10-20T05:50:10.327+0000] {standard_task_runner.py:91} INFO - Job 30: Subtask dbt_run
[2025-10-20T05:50:10.373+0000] {task_command.py:426} INFO - Running <TaskInstance: events_analytics_pipeline.dbt_run manual__2025-10-20T05:45:03.898078+00:00 [running]> on host 0d320e139cdc
[2025-10-20T05:50:10.421+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='data-team' AIRFLOW_CTX_DAG_ID='events_analytics_pipeline' AIRFLOW_CTX_TASK_ID='dbt_run' AIRFLOW_CTX_EXECUTION_DATE='2025-10-20T05:45:03.898078+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-10-20T05:45:03.898078+00:00'
[2025-10-20T05:50:10.422+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-10-20T05:50:10.429+0000] {events_pipeline_dag.py:148} INFO - Running command: dbt run --profiles-dir /opt/***/.dbt --project-dir /opt/***/event_gen
[2025-10-20T05:50:12.405+0000] {events_pipeline_dag.py:167} ERROR - dbt run failed with error:

[2025-10-20T05:50:12.405+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-10-20T05:50:12.405+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/events_pipeline_dag.py", line 175, in dbt_run
    return run_dbt_command("run", **context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/events_pipeline_dag.py", line 151, in run_dbt_command
    result = subprocess.run(
             ^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['dbt', 'run', '--profiles-dir', '/opt/airflow/.dbt', '--project-dir', '/opt/airflow/event_gen']' returned non-zero exit status 2.
[2025-10-20T05:50:12.410+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=events_analytics_pipeline, task_id=dbt_run, run_id=manual__2025-10-20T05:45:03.898078+00:00, execution_date=20251020T054503, start_date=20251020T055010, end_date=20251020T055012
[2025-10-20T05:50:12.414+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 30 for task dbt_run (Command '['dbt', 'run', '--profiles-dir', '/opt/airflow/.dbt', '--project-dir', '/opt/airflow/event_gen']' returned non-zero exit status 2.; 699)
[2025-10-20T05:50:12.443+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-10-20T05:50:12.452+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-10-20T05:50:12.453+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
