[2025-10-20T05:10:09.071+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-10-20T05:10:09.080+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: events_analytics_pipeline.setup_clickhouse_schema manual__2025-10-20T05:05:07.292852+00:00 [queued]>
[2025-10-20T05:10:09.082+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: events_analytics_pipeline.setup_clickhouse_schema manual__2025-10-20T05:05:07.292852+00:00 [queued]>
[2025-10-20T05:10:09.083+0000] {taskinstance.py:2306} INFO - Starting attempt 2 of 3
[2025-10-20T05:10:09.087+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): setup_clickhouse_schema> on 2025-10-20 05:05:07.292852+00:00
[2025-10-20T05:10:09.089+0000] {standard_task_runner.py:63} INFO - Started process 353 to run task
[2025-10-20T05:10:09.091+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'events_analytics_pipeline', 'setup_clickhouse_schema', 'manual__2025-10-20T05:05:07.292852+00:00', '--job-id', '5', '--raw', '--subdir', 'DAGS_FOLDER/events_pipeline_dag.py', '--cfg-path', '/tmp/tmpp2u22hpf']
[2025-10-20T05:10:09.092+0000] {standard_task_runner.py:91} INFO - Job 5: Subtask setup_clickhouse_schema
[2025-10-20T05:10:09.117+0000] {task_command.py:426} INFO - Running <TaskInstance: events_analytics_pipeline.setup_clickhouse_schema manual__2025-10-20T05:05:07.292852+00:00 [running]> on host aabc2cc82734
[2025-10-20T05:10:09.152+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='data-team' AIRFLOW_CTX_DAG_ID='events_analytics_pipeline' AIRFLOW_CTX_TASK_ID='setup_clickhouse_schema' AIRFLOW_CTX_EXECUTION_DATE='2025-10-20T05:05:07.292852+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-10-20T05:05:07.292852+00:00'
[2025-10-20T05:10:09.152+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-10-20T05:10:09.158+0000] {events_pipeline_dag.py:38} INFO - Connecting to ClickHouse...
[2025-10-20T05:10:09.158+0000] {events_pipeline_dag.py:41} INFO - Creating database...
[2025-10-20T05:10:09.159+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-10-20T05:10:09.159+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/events_pipeline_dag.py", line 42, in setup_clickhouse_schema
    client.execute("CREATE DATABASE IF NOT EXISTS events_db")
  File "/home/airflow/.local/lib/python3.11/site-packages/clickhouse_driver/client.py", line 361, in execute
    with self.disconnect_on_error(query, settings):
  File "/usr/local/lib/python3.11/contextlib.py", line 137, in __enter__
    return next(self.gen)
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/clickhouse_driver/client.py", line 305, in disconnect_on_error
    self.establish_connection(settings)
  File "/home/airflow/.local/lib/python3.11/site-packages/clickhouse_driver/client.py", line 292, in establish_connection
    self.connection.force_connect()
  File "/home/airflow/.local/lib/python3.11/site-packages/clickhouse_driver/connection.py", line 254, in force_connect
    self.connect()
  File "/home/airflow/.local/lib/python3.11/site-packages/clickhouse_driver/connection.py", line 395, in connect
    return self._init_connection(host, port)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/clickhouse_driver/connection.py", line 339, in _init_connection
    self.receive_hello()
  File "/home/airflow/.local/lib/python3.11/site-packages/clickhouse_driver/connection.py", line 513, in receive_hello
    raise self.receive_exception()
clickhouse_driver.errors.ServerException: Code: 516.
DB::Exception: default: Authentication failed: password is incorrect, or there is no user with such name.

If you use ClickHouse Cloud, the password can be reset at https://clickhouse.cloud/
on the settings page for the corresponding service.

If you have installed ClickHouse and forgot password you can reset it in the configuration file.
The password for default user is typically located at /etc/clickhouse-server/users.d/default-password.xml
and deleting this file will reset the password.
See also /etc/clickhouse-server/users.xml on the server where ClickHouse is installed.

. Stack trace:

0. DB::Exception::Exception(DB::Exception::MessageMasked&&, int, bool) @ 0x0000000011000530
1. DB::Exception::Exception(String&&, int, String, bool) @ 0x000000000b968d98
2. DB::Exception::Exception(PreformattedMessage&&, int) @ 0x000000000b968868
3. DB::AccessControl::authenticate(DB::Credentials const&, Poco::Net::IPAddress const&, DB::ClientInfo const&) const @ 0x0000000013fa5494
4. DB::Session::authenticate(DB::Credentials const&, Poco::Net::SocketAddress const&, std::vector<String, std::allocator<String>> const&) @ 0x000000001545ba90
5. DB::Session::authenticate(String const&, String const&, Poco::Net::SocketAddress const&, std::vector<String, std::allocator<String>> const&) @ 0x000000001545b114
6. DB::TCPHandler::receiveHello() @ 0x0000000016aac7f8
7. DB::TCPHandler::runImpl() @ 0x0000000016a9fe60
8. DB::TCPHandler::run() @ 0x0000000016abf468
9. Poco::Net::TCPServerConnection::start() @ 0x000000001b271198
10. Poco::Net::TCPServerDispatcher::run() @ 0x000000001b271734
11. Poco::PooledThread::run() @ 0x000000001b2376dc
12. Poco::ThreadImpl::runnableEntry(void*) @ 0x000000001b235a50
13. ? @ 0x0000000000080398
14. ? @ 0x00000000000e9e9c

[2025-10-20T05:10:09.163+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=events_analytics_pipeline, task_id=setup_clickhouse_schema, run_id=manual__2025-10-20T05:05:07.292852+00:00, execution_date=20251020T050507, start_date=20251020T051009, end_date=20251020T051009
[2025-10-20T05:10:09.166+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 5 for task setup_clickhouse_schema (Code: 516.
DB::Exception: default: Authentication failed: password is incorrect, or there is no user with such name.

If you use ClickHouse Cloud, the password can be reset at https://clickhouse.cloud/
on the settings page for the corresponding service.

If you have installed ClickHouse and forgot password you can reset it in the configuration file.
The password for default user is typically located at /etc/clickhouse-server/users.d/default-password.xml
and deleting this file will reset the password.
See also /etc/clickhouse-server/users.xml on the server where ClickHouse is installed.

. Stack trace:

0. DB::Exception::Exception(DB::Exception::MessageMasked&&, int, bool) @ 0x0000000011000530
1. DB::Exception::Exception(String&&, int, String, bool) @ 0x000000000b968d98
2. DB::Exception::Exception(PreformattedMessage&&, int) @ 0x000000000b968868
3. DB::AccessControl::authenticate(DB::Credentials const&, Poco::Net::IPAddress const&, DB::ClientInfo const&) const @ 0x0000000013fa5494
4. DB::Session::authenticate(DB::Credentials const&, Poco::Net::SocketAddress const&, std::vector<String, std::allocator<String>> const&) @ 0x000000001545ba90
5. DB::Session::authenticate(String const&, String const&, Poco::Net::SocketAddress const&, std::vector<String, std::allocator<String>> const&) @ 0x000000001545b114
6. DB::TCPHandler::receiveHello() @ 0x0000000016aac7f8
7. DB::TCPHandler::runImpl() @ 0x0000000016a9fe60
8. DB::TCPHandler::run() @ 0x0000000016abf468
9. Poco::Net::TCPServerConnection::start() @ 0x000000001b271198
10. Poco::Net::TCPServerDispatcher::run() @ 0x000000001b271734
11. Poco::PooledThread::run() @ 0x000000001b2376dc
12. Poco::ThreadImpl::runnableEntry(void*) @ 0x000000001b235a50
13. ? @ 0x0000000000080398
14. ? @ 0x00000000000e9e9c
; 353)
[2025-10-20T05:10:09.189+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-10-20T05:10:09.196+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-10-20T05:10:09.197+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
