[2025-10-17T04:25:55.642+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: events_analytics_pipeline.dbt_run manual__2025-10-17T04:05:48.927976+00:00 [queued]>
[2025-10-17T04:25:55.648+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: events_analytics_pipeline.dbt_run manual__2025-10-17T04:05:48.927976+00:00 [queued]>
[2025-10-17T04:25:55.650+0000] {taskinstance.py:2170} INFO - Starting attempt 3 of 3
[2025-10-17T04:25:55.656+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): dbt_run> on 2025-10-17 04:05:48.927976+00:00
[2025-10-17T04:25:55.661+0000] {standard_task_runner.py:60} INFO - Started process 1487 to run task
[2025-10-17T04:25:55.666+0000] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'events_analytics_pipeline', 'dbt_run', 'manual__2025-10-17T04:05:48.927976+00:00', '--job-id', '62', '--raw', '--subdir', 'DAGS_FOLDER/events_pipeline_dag.py', '--cfg-path', '/tmp/tmp2rpv9csu']
[2025-10-17T04:25:55.668+0000] {standard_task_runner.py:88} INFO - Job 62: Subtask dbt_run
[2025-10-17T04:25:55.710+0000] {task_command.py:423} INFO - Running <TaskInstance: events_analytics_pipeline.dbt_run manual__2025-10-17T04:05:48.927976+00:00 [running]> on host d7067dead38a
[2025-10-17T04:25:55.752+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='data-team' AIRFLOW_CTX_DAG_ID='events_analytics_pipeline' AIRFLOW_CTX_TASK_ID='dbt_run' AIRFLOW_CTX_EXECUTION_DATE='2025-10-17T04:05:48.927976+00:00' AIRFLOW_CTX_TRY_NUMBER='3' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-10-17T04:05:48.927976+00:00'
[2025-10-17T04:25:55.754+0000] {events_pipeline_dag.py:142} ERROR - dbt package not installed!
[2025-10-17T04:25:55.757+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/operators/python.py", line 199, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/operators/python.py", line 216, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/events_pipeline_dag.py", line 190, in dbt_run
    return run_dbt_command("run", **context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/events_pipeline_dag.py", line 139, in run_dbt_command
    import dbt
ModuleNotFoundError: No module named 'dbt'
[2025-10-17T04:25:55.766+0000] {taskinstance.py:1138} INFO - Marking task as FAILED. dag_id=events_analytics_pipeline, task_id=dbt_run, execution_date=20251017T040548, start_date=20251017T042555, end_date=20251017T042555
[2025-10-17T04:25:55.772+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 62 for task dbt_run (No module named 'dbt'; 1487)
[2025-10-17T04:25:55.806+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2025-10-17T04:25:55.820+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
