[2025-10-17T01:31:07.588+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: events_analytics_pipeline.dbt_run manual__2025-10-17T01:31:04.195679+00:00 [queued]>
[2025-10-17T01:31:07.591+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: events_analytics_pipeline.dbt_run manual__2025-10-17T01:31:04.195679+00:00 [queued]>
[2025-10-17T01:31:07.591+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 3
[2025-10-17T01:31:07.595+0000] {taskinstance.py:2191} INFO - Executing <Task(BashOperator): dbt_run> on 2025-10-17 01:31:04.195679+00:00
[2025-10-17T01:31:07.597+0000] {standard_task_runner.py:60} INFO - Started process 236 to run task
[2025-10-17T01:31:07.598+0000] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'events_analytics_pipeline', 'dbt_run', 'manual__2025-10-17T01:31:04.195679+00:00', '--job-id', '20', '--raw', '--subdir', 'DAGS_FOLDER/events_pipeline_dag.py', '--cfg-path', '/tmp/tmp06jlkt_6']
[2025-10-17T01:31:07.599+0000] {standard_task_runner.py:88} INFO - Job 20: Subtask dbt_run
[2025-10-17T01:31:07.615+0000] {task_command.py:423} INFO - Running <TaskInstance: events_analytics_pipeline.dbt_run manual__2025-10-17T01:31:04.195679+00:00 [running]> on host d7067dead38a
[2025-10-17T01:31:07.636+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='data-team' AIRFLOW_CTX_DAG_ID='events_analytics_pipeline' AIRFLOW_CTX_TASK_ID='dbt_run' AIRFLOW_CTX_EXECUTION_DATE='2025-10-17T01:31:04.195679+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-10-17T01:31:04.195679+00:00'
[2025-10-17T01:31:07.636+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-10-17T01:31:07.636+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'cd /opt/airflow/event_gen && /home/airflow/.local/bin/dbt run --profiles-dir /opt/airflow/.dbt --project-dir /opt/airflow/event_gen']
[2025-10-17T01:31:07.641+0000] {subprocess.py:86} INFO - Output:
[2025-10-17T01:31:07.642+0000] {subprocess.py:93} INFO - /usr/bin/bash: line 1: /home/airflow/.local/bin/dbt: No such file or directory
[2025-10-17T01:31:07.642+0000] {subprocess.py:97} INFO - Command exited with return code 127
[2025-10-17T01:31:07.646+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/operators/bash.py", line 212, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 127.
[2025-10-17T01:31:07.647+0000] {taskinstance.py:1138} INFO - Marking task as UP_FOR_RETRY. dag_id=events_analytics_pipeline, task_id=dbt_run, execution_date=20251017T013104, start_date=20251017T013107, end_date=20251017T013107
[2025-10-17T01:31:07.650+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 20 for task dbt_run (Bash command failed. The command returned a non-zero exit code 127.; 236)
[2025-10-17T01:31:07.658+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2025-10-17T01:31:07.666+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
